export const profile = [
  {
    name: 'chanelName',
    label: 'editprofile.label_chanelName',
    type: 'text',
    validations: [{ type: 'required' }, { type: 'minlength', value: 6 }],
  },
  {
    name: 'description',
    label: 'editprofile.label_description',
    type: 'textarea',
    validations: [{ type: 'minlength', value: 6 }],
  },
  { name: 'firstName', label: 'editprofile.label_firstName', type: 'text', validations: [] },
  { name: 'lastName', label: 'editprofile.label_lastName', type: 'text', validations: [] },
  { name: 'email', label: 'editprofile.label_email', type: 'text', validations: [] },
  { name: 'phoneNumber', label: 'editprofile.label_phoneNumber', type: 'text', validations: [] },
  {
    name: 'location',
    label: 'editprofile.label_location',
    type: 'text',
    validations: [],
  },
  {
    name: 'linksString',
    label: 'editprofile.label_linksString',
    type: 'array',
    placeholder: 'https://ejemplo.com',
    validations: [],
  },
  {
    name: 'socialMediaString',
    label: 'editprofile.label_socialMediaString',
    type: 'array',
    placeholder: 'https://instagram.com/usuario',
    validations: [],
  },
  {
    name: 'instantMessagesString',
    label: 'editprofile.label_instantMessagesString',
    type: 'array',
    placeholder: 'whatsapp:3201234567',
    validations: [],
  },
];
